import { Button } from '@/Components/ui/button';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, Save } from 'lucide-react';

type Employee = { id: number; employee_number: string; national_id?: string; full_name: string; email?: string; phone?: string; birth_date?: string; gender?: string; join_date: string };

export default function Edit({ employee }: { employee: Employee }) {
    const { data, setData, put, processing, errors } = useForm({ employee_number: employee.employee_number, national_id: employee.national_id ?? '', full_name: employee.full_name, email: employee.email ?? '', phone: employee.phone ?? '', birth_date: employee.birth_date ?? '', gender: employee.gender ?? '', join_date: employee.join_date });
    const field = (name: keyof typeof data, label: string, type = 'text') => <label className="block text-sm font-medium text-slate-700">{label}<input type={type} value={data[name]} onChange={event => setData(name, event.target.value)} className="mt-1 h-10 w-full rounded-[9px] border-slate-300 text-sm focus:border-green-600 focus:ring-green-600" />{errors[name] && <span className="mt-1 block text-xs text-red-600">{errors[name]}</span>}</label>;

    return <AuthenticatedLayout header={<div className="flex items-center gap-3"><Button asChild variant="ghost"><Link href={route('employees.show', employee.id)} aria-label="Kembali ke detail karyawan"><ArrowLeft size={18} /></Link></Button><div><p className="text-sm text-slate-500">Karyawan</p><h1 className="text-[26px] font-bold text-slate-900">Ubah Data Karyawan</h1></div></div>}><Head title="Ubah Data Karyawan" /><form onSubmit={event => { event.preventDefault(); put(route('employees.update', employee.id)); }} className="mx-auto max-w-4xl space-y-6 p-4 sm:p-6 lg:p-8"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-semibold text-slate-900">Identitas</h2><p className="mt-1 text-sm text-slate-500">Status dan penempatan dikelola dari halaman detail agar riwayat tetap lengkap.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{field('employee_number', 'Nomor Induk Karyawan')}{field('national_id', 'NIK (opsional)')}{field('full_name', 'Nama Lengkap')}{field('email', 'Email', 'email')}{field('phone', 'Nomor Telepon')}{field('birth_date', 'Tanggal Lahir', 'date')}{field('join_date', 'Tanggal Bergabung', 'date')}<label className="block text-sm font-medium text-slate-700">Jenis Kelamin<select value={data.gender} onChange={event => setData('gender', event.target.value)} className="mt-1 h-10 w-full rounded-[9px] border-slate-300 text-sm focus:border-green-600 focus:ring-green-600"><option value="">Tidak diisi</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></select>{errors.gender && <span className="mt-1 block text-xs text-red-600">{errors.gender}</span>}</label></div></section><div className="flex justify-end gap-3"><Button asChild type="button" variant="secondary"><Link href={route('employees.show', employee.id)}>Batal</Link></Button><Button type="submit" disabled={processing}><Save size={16} />{processing ? 'Menyimpan...' : 'Simpan Perubahan'}</Button></div></form></AuthenticatedLayout>;
}
